import 'dart:io';

import 'package:args/command_runner.dart';
import 'package:mason/mason.dart' as mason;
import 'package:mason_logger/mason_logger.dart';
import 'package:path/path.dart' as p;
import 'package:yaml/yaml.dart';

import '../bundles/chameleon_feature_bundle.dart';
import '../doctor.dart';
import '../pascal_case.dart';
import '../process_runner.dart';
import 'pipeline_steps.dart';

/// `chameleon flutter feature <name>` — adds one clean-architecture feature
/// (data/domain/presentation, a per-feature `ChopperClient`, a Bloc) to an
/// existing Chameleon app. Must be run from that app's root.
class FlutterFeatureCommand extends Command<int> with PipelineSteps {
  FlutterFeatureCommand({required this.logger, ProcessRunner? runner})
    : processRunner = runner ?? const SystemProcessRunner() {
    argParser
      ..addFlag('codegen', defaultsTo: true, help: 'Run build_runner.')
      ..addFlag(
        'verify',
        defaultsTo: true,
        help: 'Run flutter analyze + flutter test before reporting success.',
      )
      ..addFlag(
        'fvm',
        help: 'Force fvm on/off. Defaults to auto-detecting a .fvmrc.',
      );
  }

  @override
  final Logger logger;
  @override
  final ProcessRunner processRunner;

  @override
  String get name => 'feature';

  @override
  String get description =>
      'Add a clean-architecture feature to an existing Chameleon app.';

  @override
  Future<int> run() async {
    final results = argResults!;
    if (results.rest.isEmpty) {
      logger.err('Usage: chameleon flutter feature <feature_name>');
      return ExitCode.usage.code;
    }
    final featureName = results.rest.first;

    if (!RegExp(r'^[a-z][a-z0-9_]*$').hasMatch(featureName)) {
      logger.err(
        '"$featureName" is not a valid feature name '
        '(snake_case, must start with a lowercase letter).',
      );
      return ExitCode.usage.code;
    }

    final projectRoot = Directory.current;

    // The same provenance file `create`'s post_gen hook writes — its
    // absence means this isn't a Chameleon app root, and generating into
    // the wrong directory (e.g. the toolchain repo itself) would be a real
    // mess to clean up by hand, so fail loudly before mason touches
    // anything.
    final provenance = File(
      p.join(projectRoot.path, '.chameleon', 'template.yaml'),
    );
    if (!provenance.existsSync()) {
      logger.err(
        'No .chameleon/template.yaml found in ${projectRoot.path}.\n'
        'Run `chameleon flutter feature` from the root of a Chameleon app '
        'generated by `chameleon flutter create`.',
      );
      return ExitCode.usage.code;
    }

    final featureDir = Directory(
      p.join(projectRoot.path, 'lib', 'features', featureName),
    );
    if (featureDir.existsSync()) {
      logger.err(
        'lib/features/$featureName already exists. chameleon_feature does '
        'not overwrite an existing feature.',
      );
      return ExitCode.usage.code;
    }

    // The generated feature's tests import the app's own lib code via
    // `package:<project_name>/...` — read the real package name from the
    // app's own pubspec.yaml rather than re-deriving it, so this works even
    // if the project was renamed after `chameleon flutter create`.
    final pubspecFile = File(p.join(projectRoot.path, 'pubspec.yaml'));
    final pubspecYaml = loadYaml(pubspecFile.readAsStringSync()) as YamlMap;
    final projectName = pubspecYaml['name'] as String;

    final doctor = Doctor(runner: processRunner);
    final report = await doctor.check(directory: projectRoot.path);
    if (!report.isUsable) {
      logger.err(
        'Toolchain is not usable — run `chameleon doctor` for details.',
      );
      return ExitCode.unavailable.code;
    }

    final useFvm = (results['fvm'] as bool?) ?? report.useFvm;
    final flutterExecutable = useFvm ? 'fvm' : 'flutter';
    final flutterPrefix = useFvm ? const ['flutter'] : const <String>[];
    final dartExecutable = useFvm ? 'fvm' : 'dart';
    final dartPrefix = useFvm ? const ['dart'] : const <String>[];

    final vars = <String, dynamic>{
      'feature_name': featureName,
      'project_name': projectName,
    };

    final generated = await step('Generating feature "$featureName"', () async {
      final generator = await mason.MasonGenerator.fromBundle(
        chameleonFeatureBundle,
      );
      Map<String, dynamic>? updatedVars;
      await generator.hooks.preGen(
        vars: vars,
        workingDirectory: projectRoot.path,
        onVarsChanged: (v) => updatedVars = v,
      );
      await generator.generate(
        mason.DirectoryGeneratorTarget(projectRoot),
        vars: updatedVars ?? vars,
        fileConflictResolution: mason.FileConflictResolution.overwrite,
      );
      await generator.hooks.postGen(
        vars: updatedVars ?? vars,
        workingDirectory: projectRoot.path,
      );
    });
    if (!generated) return ExitCode.software.code;

    if (results['codegen'] as bool) {
      final ok = await step(
        'Running build_runner',
        () => exec(dartExecutable, [
          ...dartPrefix,
          'run',
          'build_runner',
          'build',
          '--delete-conflicting-outputs',
        ], cwd: projectRoot.path),
      );
      if (!ok) return ExitCode.software.code;
    }

    if (results['verify'] as bool) {
      final verified = await verify(
        projectRoot.path,
        flutterExecutable,
        flutterPrefix,
      );
      if (!verified) return ExitCode.software.code;
    }

    logger
      ..info('')
      ..success('lib/features/$featureName is ready.')
      ..info('')
      ..info('Next:')
      ..info(
        '  Fill in the real fields on the entity/model — id/name are a placeholder.',
      )
      ..info('  Wire ${pascalCase(featureName)}Page into your router.')
      ..info(
        "  If this endpoint needs no-auth/idempotency config, see core_module.dart's TODO.",
      );
    return ExitCode.success.code;
  }
}
